export const projectPages = [
	{
		title: 'Find My Pet',
		description: '',
		images: ['/find_my_pet.png'],
		technologies: [
			'NextJS',
			'MongoDB',
			'TypeScript',
			'TailwindCSS',
			'GraphQL',
			'Context API',
			'PetFinder API',
		],
		url: '/',
		github: '/',
	},
	{
		title: 'Dungeons and Dragons Player Sheet',
		description: '',
		images: ['/dungeons_and_dragons.png'],
		technologies: [
			'ReactJS',
			'MongoDB',
			'Node.js',
			'Redux Toolkit',
			'Material UI',
		],
		url: '/',
		github: '/',
	},
	{
		title: 'Photography Blog',
		description: '',
		images: ['/photography_blog.png'],
		technologies: ['NextJS', 'Sanity.io', 'TypeScript', 'TailwindCSS'],
		url: '/',
		github: '/',
	},
	{
		title: 'The District Eye Care Landing Page',
		description: '',
		images: ['/district_eye.png'],
		technologies: ['NextJS', 'TailwindCSS'],
		url: '/',
		github: '/',
	},
]
